### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by shock-dev** [vrpv/Proekt#4]
hm.

**Comment by shock-dev** [comment]
😏

**Comment by vrpv** [comment]
Приветики

**Comment by shock-dev** [comment]
ебать

**Comment by shock-dev** [comment]
яж говорю сокеты

**Comment by shock-dev** [comment]
нука а так **пываыва**

**Comment by shock-dev** [comment]
а вот так _аывавы_

**Comment by vrpv** [comment]
Найс

**Comment by shock-dev** [comment]
а если 

> это`

**Comment by vrpv** [comment]
Я те говорил - реакт учи

**Comment by shock-dev** [comment]
крч закрывай я понял, шарю теперь

**Comment by vrpv** [comment]
ты создал, вот и закрывай

**Comment by shock-dev** [comment]
да я хочу чтоб ты закрыл, типо ты ответил на мой вопрос
и как создатель репо закрыл
